version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: veiculos123        # Senha do root
      MYSQL_DATABASE: veiculosdb              # Banco que será criado automaticamente
      MYSQL_USER: veiculos_user               # Usuário da aplicação
      MYSQL_PASSWORD: veiculos_pass           # Senha do usuário
    ports:
      - "3307:3306"                           # Porta local 3307 -> porta 3306 do container
    volumes:
      - my-db-volume:/var/lib/mysql           # Persistência dos dados

volumes:
  my-db-volume: